services:

  simple_kafka_pipeline:
    build: ./simple_kafka_pipeline
    networks:
      - kafka-network
    volumes: 
      - simple_kafka_pipeline-logs:/root/.m2/repository/com/pipeline/kafka/simple_kafka_pipeline/1.0-SNAPSHOT

  data_generator:
    build: ./data_generator
    networks:
      - kafka-network
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: "docker"
    volumes:
      - data-generator-datasets:/project/datasets
    
  zookeeper:
    image: 'bitnami/zookeeper:3.8.2'
    ports: 
      - "2181:2181"
    networks: 
      - kafka-network
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes: 
      - zookeeper-logs:/bitnami/zookeeper
    
  kafka: 
    image: 'bitnami/kafka:3.5'
    ports: 
      - "9092:9092"
      - "9094:9094"
    networks:
      - kafka-network
    environment: 
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://localhost:9094
    volumes: 
      - kafka-logs:/bitnami/kafka
    depends_on:
      zookeeper:
        condition: service_started

  anonymized_kafka:
    build: ./anonymized_kafka
    networks:
      - kafka-network
    depends_on:
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
    volumes: 
    - ./anonymized_kafka_config/default_anonymized_kafka.json:/tmp/default_anonymized_kafka.json

  kafka-connect:
    image: 'bitnami/kafka:3.5'
    ports:
      - "8079:8083"
    networks:
      - kafka-network
    depends_on:
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
      simple_kafka_pipeline:
        condition: service_completed_successfully
      data_generator:
        condition: service_completed_successfully
    volumes:
      - ./kafka_connect_config/connect-standalone.properties:/opt/bitnami/kafka/config/connect-standalone.properties
      - ./kafka_connect_config/CSVSourceConnector.properties:/opt/bitnami/kafka/config/CSVSourceConnector.properties
      - ./kafka_connect_config/entrypoint.sh:/entrypoint.sh
      - simple_kafka_pipeline-logs:/custom-jars
      - data-generator-datasets:/data-generator-datasets
    command: /entrypoint.sh
  
networks: 
  kafka-network:
    driver: bridge

volumes:
  simple_kafka_pipeline-logs:
  data-generator-datasets:
  zookeeper-logs:
  kafka-logs: