services:

  anonymized_kafka:
    build: ./anonymized_kafka
    networks:
      - kafka-network
    volumes: 
      - /tmp/kafka-anonymized-logs:/root/.m2/repository/com/pipeline/kafka/anonymized_kafka/1.0-SNAPSHOT/
    command: install

  data_generator:
    build: ./data_generator
    networks:
      - kafka-network
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: "docker"
    volumes:
      - '/tmp/data_generator/syntheticData.csv:/project/syntheticData.csv'
    
  zookeeper:
    image: 'bitnami/zookeeper:3.8.2'
    ports: 
      - "2181:2181"
    networks: 
      - kafka-network
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes: 
      - '/tmp/zookeeper-logs:/bitnami/zookeeper'
    
  kafka: 
    image: 'bitnami/kafka:3.5'
    ports: 
      - "9092:9092"
    networks:
      - kafka-network
    environment: 
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_mounts/logs
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes: 
      - '/tmp/kafka-logs:/bitnami/kafka'
    depends_on:
      - zookeeper

  kafka-connect:
    image: 'bitnami/kafka:3.5'
    ports:
      - "8079:8083"
    networks:
      - kafka-network
    depends_on:
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
      anonymized_kafka:
        condition: service_completed_successfully
    volumes:
      - './kafka_connect_config/connect-standalone.properties:/opt/bitnami/kafka/config/connect-standalone.properties'
      - './kafka_connect_config/CSVSourceConnector.properties:/opt/bitnami/kafka/config/CSVSourceConnector.properties'
      - '/tmp/kafka-anonymized-logs/anonymized_kafka-1.0-SNAPSHOT-jar-with-dependencies.jar:/opt/bitnami/kafka/libs/anonymized_kafka-1.0-SNAPSHOT-jar-with-dependencies.jar'
      - '/tmp/data_generator/syntheticData.csv:/tmp/syntheticData.csv'
    command: /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/config/connect-standalone.properties /opt/bitnami/kafka/config/CSVSourceConnector.properties

networks: 
  kafka-network:
    driver: bridge
