services:
  kafka: 
    image: 'bitnami/kafka:3.5'
    ports: 
      - '9092:9092'
    networks:
      - kafka-network
    environment: 
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes: 
      - /tmp/kafka-logs:/bitnami/kafka

  kafka-connect:
    image: 'bitnami/kafka:3.5'
    ports:
      - '8083:8083'
    networks:
      - kafka-network
    volumes:
      - './kafka_connect_config/connect-distributed.properties:/opt/bitnami/kafka/config/connect-distributed.properties'
    depends_on:
      - kafka
    command: /opt/bitnami/kafka/bin/connect-distributed.sh /opt/bitnami/kafka/config/connect-distributed.properties

#zookeeper:

#data_generator:

#anonymized_kafka:

networks: 
  kafka-network:
    driver: bridge